function [ cdfData ] = setupCdfRecords( cdfInfoMaster )

% initialize cdf matrixes/vectors with space allocated for 100 entries
    numEntries = 1000;
    cdfData = struct( 'chorusEpoch', int64(zeros(numEntries, cdfInfoMaster.Variables{1,2}(1))), ...
                      'frequency', cdfInfoMaster.VariableAttributes.FILLVAL{4,2} * ones(numEntries, cdfInfoMaster.Variables{4,2}(1)), ...
                      'psd', cdfInfoMaster.VariableAttributes.FILLVAL{5,2} * ones(numEntries, cdfInfoMaster.Variables{5,2}(1)), ...
                      'sweeprate', single( cdfInfoMaster.VariableAttributes.FILLVAL{6,2}) * zeros(numEntries, cdfInfoMaster.Variables{6,2}(1)), ...
                      'burst', int32(zeros(numEntries, cdfInfoMaster.Variables{7,2}(1))), ...
                      'chorusIndex', int32(zeros(numEntries, cdfInfoMaster.Variables{8,2}(1))));
end

